name             'sep_management'
maintainer       'SDl Plc'
maintainer_email 'rrahman@sdl.com'
license          'All rights reserved'
description      'Performs Base installation of SEP Management Server'
version			 '1.3.0'
depends			 'windows'
